**Indexing & Slicing of Vectors**

In [3]:
import numpy as np
arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [9]:
print(arr[0])
print(arr[4])
print(arr[:4])
print(arr[1:5:2])

11
15
[11 12 13 14]
[12 14]


**Indexing & Slicing of Matrix**

In [11]:
arr = np.arange(1,31).reshape([6,5])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [18]:
print(arr[0])
print(arr[1,2])
print(arr[0:2,1:3])
print(arr[3:,3:])
print(arr[:,2])

[1 2 3 4 5]
8
[[2 3]
 [7 8]]
[[19 20]
 [24 25]
 [29 30]]
[ 3  8 13 18 23 28]


**Boolean Indexing**

In [34]:
arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [35]:
bool_index = arr%2 == 0
print(bool_index)

[False  True False  True False  True False  True False  True]
