**Array Operations (Arithmatic Operations)**

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
result = arr1+arr2
print(result)


[ 7  9 11 13 15]


**Broadcasting**

In [ ]:
l = [10,20,30,40]
arr = np.array(l)
print(arr+10)

[20 30 40 50]


**Deep Copy**

In [ ]:
a = np.array([1,2,3,4,5])
b=a.copy()

b[0] = 10
print(a)
print(b)

[1 2 3 4 5]
[10  2  3  4  5]


**Shallow Copy**

In [ ]:
a = np.array([1,2,3,4,5])
b=a.view()

b[0] = 10
print(a)
print(b)

[10  2  3  4  5]
[10  2  3  4  5]


**Matrix Operation**

In [ ]:
A = np.array([[1,2],[4,5]])
B = np.array([[7,8],[10,11]])
print(A)
print(B)
print(A*B)
print(A @ B)
print(np.dot(A,B))
print(A.T)

[[1 2]
 [4 5]]
[[ 7  8]
 [10 11]]
[[ 7 16]
 [40 55]]
[[27 30]
 [78 87]]
[[27 30]
 [78 87]]
[[1 4]
 [2 5]]
