**Problem 1 – Student Marks Analysis**

In [4]:
import numpy as np
arr = np.array([78, 85, 92, 67, 88, 95, 73, 81, 90, 76]) # Create the array
print(arr.shape) # Shape
print(arr.size) # Size
print(arr.ndim) # Dimension
print(arr.dtype) # Data Type
print(arr.astype(float)) # Change type to float
print(arr[:5]) # Print the first 5 marks
print(arr[7:]) # Print the last 3 marks.

(10,)
10
1
int64
[78. 85. 92. 67. 88. 95. 73. 81. 90. 76.]
[78 85 92 67 88]
[81 90 76]


**Problem 2 – Random Sales Data**

In [16]:
import numpy as np
arr = np.random.randint(1000,5000,30) # Generate 30 random integers between 1000 and 5000
print(arr)
print(arr.max()) # Max
print(arr.min()) # Min
print(arr.sum()) # Sum
print(arr.mean()) # Mean or Average
bool_index = arr > 3000
print(sum(bool_index)) # Count how many days had sales greater than 3000
print(np.sort(arr)) # Sort

[1864 1607 4695 1987 1130 2719 2336 4717 2327 3996 1661 4486 1430 1823
 3615 2824 4855 1546 3739 1329 2932 4394 4472 3418 4346 2104 4068 2214
 2429 4611]
4855
1130
89674
2989.133333333333
13
[1130 1329 1430 1546 1607 1661 1823 1864 1987 2104 2214 2327 2336 2429
 2719 2824 2932 3418 3615 3739 3996 4068 4346 4394 4472 4486 4611 4695
 4717 4855]


**Problem 3 – Exam Statistics**

In [29]:
import numpy as np
from statistics import mode
marks_arr = np.array([55, 60, 72, 90, 85, 60, 75, 90, 100, 72])
print(mode(marks_arr)) # Mode
print(np.median(marks_arr)) # Median
print(np.std(marks_arr)) # Standard Deviation
print(np.var(marks_arr)) # varaiance
mean = np.mean(marks_arr)
print(mean) # Mean
more = marks_arr>mean
mask = more
print(marks_arr[mask]) # Print students scoring above the mean

exact = marks_arr == 90
print(sum(exact)) # Count how many students scored exactly 90



60
73.5
14.264992113562489
203.48999999999998
75.9
[ 90  85  90 100]
2


**Problem 4 – Employee Salary Matrix**

In [42]:
import numpy as np
Mat_arr = np.array([25000, 27000, 30000, 32000, 35000, 37000, 40000, 42000, 45000, 47000, 50000, 52000])
matrix = Mat_arr.reshape(3,4) # Convert it into a 3 × 4 matrix
print(matrix)
print(matrix[1]) # Row 1
print(matrix[:,2]) # Column 2
matrix.resize((2,6)) # Resize it into a 2 × 6 array
print(matrix)
print(matrix.flatten("C")) # Flatten the matrix back into a 1D array


[[25000 27000 30000 32000]
 [35000 37000 40000 42000]
 [45000 47000 50000 52000]]
[35000 37000 40000 42000]
[30000 40000 50000]
[[25000 27000 30000 32000 35000 37000]
 [40000 42000 45000 47000 50000 52000]]
[25000 27000 30000 32000 35000 37000 40000 42000 45000 47000 50000 52000]


**Problem 5 – Weather Temperature Analysis**

In [68]:
import numpy as np
weather = np.random.randint(20,40,14) # Create the array
print(weather)
re_shape = weather.reshape(2,7) # Reshape it into a 2 × 7 matrix (2 weeks)
print(re_shape)
# Weekly Average Temp
week_1 = re_shape[0]
print(week_1.mean())
week_2 = re_shape[1]
print(week_2.mean())

print(weather.mean()) # Overall average
print(weather.max()) # Highest temperature
print(weather.min()) # Lowest tempreture
print(weather.std()) # Standard Deviation
print(weather.var()) # variance
temp = weather>35 # Print all temperatures above 35°C.
print(weather[temp])
re_shape.resize((7,2)) # Resize the array into 7 × 2.
print(re_shape)


[26 39 37 30 31 26 35 29 28 23 24 35 24 22]
[[26 39 37 30 31 26 35]
 [29 28 23 24 35 24 22]]
32.0
---------------------
26.428571428571427
29.214285714285715
39
22
5.3073879966456925
28.168367346938776
[39 37]
[[26 39]
 [37 30]
 [31 26]
 [35 29]
 [28 23]
 [24 35]
 [24 22]]
