**Create Array**

In [3]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr*2)

[2 4 6 8]


In [7]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
arr = np.zeros((4,8))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [21]:
arr = np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


**Random Generation Functions**

In [37]:
arr = np.random.rand(5)
print(arr)

[0.32138105 0.0139417  0.02310935 0.0607561  0.73249127]


In [30]:
arr = np.random.randn(5)
print(arr)

[-1.11969081 -0.28634626 -0.62764557  1.23407178  1.24502471]


In [83]:
arr = np.random.randint(1,5)
print(arr)

4


**Array Attributes**

In [84]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 3)
9
int64
2


**Array Methods**

In [99]:
arr = np.array([[1,2,3],[4,4,6],[7,8,9]])
print(arr.std())
print(arr.var())
print(arr.min())
print(arr.max())
print(np.sum(arr,axis = 0))
print(np.sum(arr,axis = 1))
print(arr.sum())
print(arr.argmin())
print(arr.argmax())
print(np.mean(arr))
print(np.median(arr))

2.601044424604361
6.765432098765432
1
9
[12 14 18]
[ 6 14 24]
44
0
8
4.888888888888889
4.0


In [101]:
from statistics import mode

arr = [1, 2, 2, 3, 4, 5]

print(mode(arr))

2


**ReSizing & ReShaping**

In [103]:
arr = np.arange(1,31)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [106]:
print(arr.reshape(6,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [110]:
print(arr.resize(5,5))
print(arr)

None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
